Group3Project/Group3Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("UweFlixx.urls")),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

uweflix/urls.py
from django.urls import path
from uweflix import views
from uweflix.models import *
from .views import *


urlpatterns = [
    path("club_discount/", views.clubdiscount, name="club_discount"),
    path("change_account_page/", views.change_account_page, name="change_account_page"),
    path("update_accounts_form_page/", views.update_accounts_form_page, name="update_accounts_form_page"),
    path('add_user', add_user, name='add_user'),
    path('delete_user/<int:myid>/', delete_user, name='delete_user'),
    path('edit_user/<int:myid>/', edit_user, name='edit_user'),
    path('update_user/<int:myid>/', update_user, name='update_user'),
    path('manage_club_account/', views.manage_club_account, name='manage_club_account'),
    path('add_clubs', add_clubs, name='add_clubs'),
    path('card_payment_form/<str:payment_method>/', views.card_payment_form, name='card_payment_form'),
    path('delete_clubs/<int:myid>/', delete_clubs, name='delete_clubs'),
    path('edit_clubs/<int:myid>/', edit_clubs, name='edit_clubs'),
    path('update_clubs/<int:myid>/', update_clubs, name='update_clubs'),
    
    
    path('modify_delete_accounts/', views.modify_delete_accounts,
         name='modify_delete_accounts'),
    path('create_account/', create_account, name='create_account'),
    path('delete_account/<int:myid>/', delete_account, name='delete_account'),
    path('edit_account/<int:myid>/', edit_account, name='edit_account'),
    path('update_account/<int:myid>/', update_account, name='update_account'),
    path('view_account/', view_account, name='view_account'),

    
    
    
    path("", views.viewings_page, name="home"),
    path("viewings_page/", views.viewings_page, name="viewings_page"),
    path("showings/<int:film>/", views.showings, name="showings_by_film"),
    path("add_new_movie/", views.add_new_movie, name="add_new_movie"),
    path("films_endpoint/", views.films_endpoint, name="films_endpoint"),
    path("specific_film_endpoint/<int:pk>/", views.specific_film_endpoint, name="specific_film_endpoint"),
    path("login/", views.login, name="login"),
    path("topup/", views.topup, name="topup"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.registerPage, name="registerPage"),
    path("payment/<int:showing>/", views.payment, name="payment"),
    path('payment_page_for_representative/<int:showing>/', views.payment_page_for_representative, name='payment_page_for_representative'),
    path("card_payment_form/", views.card_payment_form, name="card_payment_form"),
    path("view_accounts/", views.view_accounts, name="view_accounts"),
    path("daily_transactions/", views.daily_transactions, name="daily_transactions"),
    path("customer_statements/", views.customer_statements, name="customer_statements"),
    path("thanks/", views.thanks, name="thanks"),
    path("user/", views.userpage, name="user-page"),
    path("new_club_add_page/", views.new_club_add_page, name="new_club_add_page"),
    path("clubs_endpoint/", views.clubs_endpoint, name="clubs_endpoint"),
    path("specific_club_endpoint/<int:pk>/", views.specific_club_endpoint, name="specific_club_endpoint"),
    path("adding_new_representative_page/", views.adding_new_representative_page, name="adding_new_representative_page"),
    path("club_rep_home/", views.club_rep_home, name="club_rep_home"),
    path("cinema_manager_home/", views.cinema_manager_home, name="cinema_manager_home"),
    path("student_home/", views.student_home, name="student_home"),
    path("set_payment/", views.set_payment_details, name="set_payment"),
    path("main_home_page/", views.main_home_page, name="main_home_page"),
    path("payment_settle_page/", views.payment_settle_page, name="payment_settle_page"),
    path("review_students/<int:userID>", views.review_students, name="review_students"),
    path("rep_success/", views.rep_success, name="rep_success"),
    path("change_ticket_prices/", views.change_ticket_prices, name="change_ticket_prices"),
    path("view_order_history/", views.view_order_history, name="view_order_history"),
    path("request_cancellation/", views.request_cancellation, name="request_cancellation"),
    path("cancel_payment_aprovement_page/", views.approve_cancellation, name="cancel_payment_aprovement_page"),
    path("screens_endpoint/", views.screens_endpoint, name="screens_endpoint"),
    path("specific_screen_endpoint/<int:pk>/", views.specific_screen_endpoint, name="specific_screen_endpoint"),
    path("New_screen_addition_page/", views.New_screen_addition_page, name="New_screen_addition_page"),
    path("add_new_showing_screen/", views.add_new_showing_screen, name="add_new_showing_screen"),
    path('update_showings_page/<int:showing_id>/', views.update_showings_page, name='update_showings_page'),

    path('movie/<int:movie_id>/', get_movie_details, name='get_movie_details'),
    path('now_playing/', get_now_playing_movies, name='now_playing'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("uweflix.urls")),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

uweflix/models.py
from email import charset
from pyexpat import model
from tokenize import String
from xml.dom.minidom import CharacterData
from django.db import models
from django.contrib.auth.models import *
from datetime import datetime as dt
import datetime
import random


from django.forms import ValidationError

class User(AbstractUser):
    pass

class Customer(models.Model):  # Student accounts
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField('Date Of Birth')
    credit = models.FloatField(default=0.00)

class Transaction(models.Model):
    customer = models.ForeignKey(Customer, blank=True, null=True, default=None, on_delete=models.SET_DEFAULT)
    date = models.DateField()
    cost = models.FloatField()
    is_settled = models.BooleanField()
    request_to_cancel = models.BooleanField(default=False)
    
    @staticmethod
    def load_new_transactions(transaction_id):
        try:
            transaction = Transaction.objects.get(id=transaction_id)
            return transaction
        except:
            print("No transaction exists")
            
    @classmethod
    def create_new_transaction(cls, cust, cost, is_paid):
        try:
            transaction = cls.objects.create(customer=cust, date=dt.today(), cost=cost, is_settled=is_paid)
            return transaction
        except:
            print("Transaction could not be made.")

    @staticmethod
    def update_existing_transaction(id, **transaction_data):
        try:
            update_fields = {}
            for key, value in transaction_data.items():
                if key in ['customer', 'date', 'cost', 'is_settled']:
                    update_fields[key] = value

            Transaction.objects.filter(pk=id).update(**update_fields)
            return Transaction.objects.get(id=id)
        except:
            print("Error.")

    @staticmethod
    def delete_existing_transaction(id):
        try:
            transaction = Transaction.objects.get(id=id)
            transaction.delete()
        except:
            print("This transaction does not exist, or had an issue being deleted.")



from django.db import models

class Film(models.Model):
    AGE_RATING_CHOICES = [
        ('U', 'U'),
        ('PG', 'PG'),
        ('12', '12'),
        ('12A', '12A'),
        ('15', '15'),
        ('18', '18'),
    ]

    title = models.CharField(max_length=100)
    age_rating = models.CharField(max_length=3, choices=AGE_RATING_CHOICES)
    duration = models.CharField(max_length=3)  # Store duration in minutes only (e.g. 120)
    trailer_desc = models.CharField(max_length=500)
    image = models.ImageField(default="placeholder.png")

    @classmethod
    def create_new_film(cls, title, age_rating, duration, trailer_desc):
        try:
            film = cls.objects.create(title=title, age_rating=age_rating, duration=duration, trailer_desc=trailer_desc)
            return film
        except:
            print("Film could not be added")

    @classmethod
    def read_created_film(cls, id):
        try:
            film = cls.objects.get(id=id)
            return film
        except:
            print("Film could not be found")

    @classmethod
    def delete_existing_film(cls, id):
        try:
            film = cls.objects.get(id=id)
            if not Showing.objects.exists(film=film):
                film.delete()
            else:
                print("The selected Item has showings going on, therefore it cannot be deleted")
        except:
            print("Could not be deleted")

    @classmethod
    def update_existing_film(cls, id, *field_to_edit):
        try:
            for field in field_to_edit:
                if isinstance(field, str):
                    cls.objects.filter(id=id).update(title=field)
                elif isinstance(field, int):
                    cls.objects.filter(id=id).update(age_rating=field)
            return cls.objects.get(id=id)
        except:
            print("Film could not be updated")

    def __str__(self):
        return self.title


from django.db import models

class Screen(models.Model):
    capacity = models.IntegerField()
    apply_covid_restrictions = models.BooleanField(null=True)

    def __str__(self):
        return "Screen " + str(self.id)

    @classmethod
    def create_new_Screen(cls, seats, covid_restrictions):
        try:
            screen = cls.objects.create(capacity=seats, apply_covid_restrictions=covid_restrictions)
            return screen
        except:
            print("Screen cannot be created, perhaps you are missing some parameters?")

    @classmethod
    def read_existing_screen(cls, id):
        try:
            screen = cls.objects.get(id=id)
            return screen
        except:
            print("Screen cannot be found, perhaps you have entered an incorrect id?")

    @classmethod
    def update_EXisting_Screen(cls, id, field_to_edit):
        try:
            if isinstance(field_to_edit, bool):
                cls.objects.filter(id=id).update(apply_covid_restrictions=field_to_edit)
            elif isinstance(field_to_edit, (int, float)):
                cls.objects.filter(id=id).update(capacity=field_to_edit)
            return cls.objects.get(id=id)
        except Exception as e:
            print("Screen cannot be found, perhaps you have entered an invalid field type?")
            print(e)

    @classmethod
    def delete_existing_screen(cls, id):
        try:
            screen = cls.objects.get(id=id)
            screen.delete()
        except:
            print("Screen cannot be found, perhaps you have entered an incorrect id?")



class Showing(models.Model):
    screen = models.ForeignKey(Screen, default=1, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    time = models.DateTimeField()
    remaining_tickets = models.IntegerField(default=150)

    @classmethod
    def newShowing(cls, screen, film, time):
        try:
            showing = cls.objects.create(screen=screen, film=film, time=time, remaining_tickets=screen.capacity)
            if screen.apply_covid_restrictions:
                showing.remaining_tickets = showing.remaining_tickets // 2
                showing.save()
            return showing
        except:
            print("Cannot create this new showing!")

    @classmethod
    def find_existing_showing(cls, id):
        try:
            showing = cls.objects.get(id=id)
            return showing
        except:
            print("No such showing available!.")

    @classmethod
    def modify_existing_showing(cls, id, *showing_data):
        try:
            for data_item in showing_data:
                if isinstance(data_item, Screen):
                    cls.objects.filter(pk=id).update(screen=data_item)
                elif isinstance(data_item, Film):
                    cls.objects.filter(pk=id).update(film=data_item)
                elif isinstance(data_item, float):
                    cls.objects.filter(pk=id).update(time=data_item)
                elif isinstance(data_item, int):
                    cls.objects.filter(pk=id).update(remaining_tickets=data_item)
                elif isinstance(data_item, bool):
                    cls.objects.filter(pk=id).update(apply_covid_restrictions=False)
                else:
                    print(f"Data item {data_item} does not meet the requirements.." +
                          "\n Cannot update this.")
            return cls.objects.get(id=id)
        except:
            print("error")

    @classmethod
    def remove_existing_showing(cls, id):
        try:
            showing = cls.objects.get(id=id)
            showing.delete()
        except:
            print("Showing is deleted, Bye!.")



class Ticket(models.Model):
    transaction = models.ForeignKey(Transaction, default=1, on_delete=models.SET_DEFAULT)
    showing = models.ForeignKey(Showing, default=1, on_delete=models.SET_DEFAULT)
    ticket_type = models.CharField(max_length=7)

    @classmethod
    def create_ticket(cls, trans, show, ticket_type):
        try:
            ticket = cls.objects.create(transaction=trans, showing=show, ticket_type=ticket_type)
            return ticket
        except:
            print("Error, wrong parameter!")

    @classmethod
    def find_ticket(cls, id):
        try:
            ticket = cls.objects.get(id=id)
            return ticket
        except:
            print("Ticket cannot be found, perhaps you have entered an incorrect id?")

    @classmethod
    def modify_ticket(cls, id, *fields_to_edit):
        try:
            for field in fields_to_edit:
                if isinstance(field, Transaction):
                    cls.objects.filter(id=id).update(transaction=field)
                elif isinstance(field, Showing):
                    cls.objects.filter(id=id).update(showing=field)
                elif isinstance(field, str):
                    cls.objects.filter(id=id).update(ticket_type=field)
            return cls.objects.get(id=id)
        except:
            print("Cannot update, wrong field type!")

    @classmethod
    def delete_ticket(cls, id):
        try:
            ticket = cls.objects.get(id=id)
            ticket.delete()
        except:
            print("Ticket cannot be found, perhaps you have entered an invalid id?")



class Club(models.Model):
    name = models.CharField(max_length=65)
    street_number = models.IntegerField()
    street = models.CharField(max_length=66)
    city = models.CharField(max_length=43)
    post_code = models.CharField(max_length=10)
    landline_number = models.CharField(max_length=13)
    mobile_number = models.CharField(max_length=13)
    email = models.EmailField(max_length=1333)
    card_number = models.IntegerField(blank=True, null=True)
    card_expiry_date = models.DateField(blank=True, null=True)
    discount_rate = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    @classmethod

uweflix/templates/uweflix/add_new_movie.html
{% extends "uweflix/layout.html" %}
{% block title %}
Manage Movies
{% endblock %}
{% block header %}
Manage Movies
{% endblock %}
{% block content %}

  <div class="panel">
    <h2>Add Movie</h2>
    <div class="row">

      <div class="box-element" id="form-wrapper">
        <form id="form" method="POST" enctype="multipart/form-data"> {% csrf_token %} <div id="film-info">
            <div class="form-field">
              <input required class="form-control" type="text" name="title" placeholder="Title.." maxlength="100">
            </div>
            <div class="form-field">
              <select required class="form-control" name="age_rating">
                <option value="" disabled selected hidden>Age Rating..</option>
                <option value="U">U</option>
                <option value="PG">PG</option>
                <option value="12">12</option>
                <option value="12A">12A</option>
                <option value="15">15</option>
                <option value="18">18</option>
              </select>
            </div>
            <div class="form-field">
              <input required class="form-control" type="number" name="duration" placeholder="Duration.." maxlength="3">
            </div>
            <div class="form-field">
              <input required class="form-control" type="text" name="trailer_desc" placeholder="Trailer Description.."
                maxlength="500">
            </div>
            <div class="form-field"> (Optional) Image: <input class="form-control" type="file" accept="image/*"
                name="image">
            </div>
          </div>
          <hr>
          <input type="submit" value="Add Film" class="button">
        </form>

      </div>
    </div>
  </div>

  <div class="panel">
    <h2>Delete Movie</h2>
    <div class="box-element" id="form-wrapper">
      <form id="form" method="POST"> {% csrf_token %} {{ form.as_p }}
        <hr>
        <input type="submit" name="delete_film" value="Delete Film" class="button">
      </form>
    </div>
  </div>

  <div class="panel">
    <h2>Edit Movie Details</h2>
    <div class="box-element" id="form-wrapper">
      <form id="form" method="POST"> {% csrf_token %}        {{ form.as_p }}
        <hr>
        <div id="film-info">
          <div class="form-field">
            <input required class="form-control" type="text" name="edit_title" placeholder="Title.." maxlength="100">
          </div>
          <div class="form-field">
            <select required class="form-control" name="edit_age_rating">
              <option value="" disabled selected hidden>Age Rating..</option>
              <option value="U">U</option>
              <option value="PG">PG</option>
              <option value="12">12</option>
              <option value="12A">12A</option>
              <option value="15">15</option>
              <option value="18">18</option>
            </select>
          </div>
          <div class="form-field">
            <input required class="form-control" type="number" name="edit_duration" placeholder="Duration.."
              maxlength="3">
          </div>
          <div class="form-field">
            <input required class="form-control" type="text" name="edit_trailer_desc"
              placeholder="Trailer Description.." maxlength="500">
          </div>
          <div class="form-field"> (Optional) Image: <input class="form-control" type="file" accept="image/*"
              name="edit_image">
          </div>
        </div>
        <hr>
        <input type="submit" name="edit_film" value="Edit Film" class="button">
      </form>
    </div>
  </div>
 
{% endblock %}

uweflix/templates/uweflix/club_rep_home.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Club Rep Home Page
{% endblock %}
{% block header %}
Management Panel
{% endblock %}
{% block content %}

<div class="container">

  <div class="panel">
    <div class="h1"></div>
    <h1>Book Film</h1></br>
    <h2>Book a viewing!</h2></br>
    <a href="{% url 'viewings_page' %}">
      <input type="button" value="Book" class="button" />
    </a>
    <div class="h1"></div>
  </div>

  <div class="panel">
    <div class="h1"></div>
    <h1>Topup Credit</h1></br>
    <h2>£{{ request.session.credit|floatformat:2 }} left!</h2></br>
    <a href="{% url 'topup' %}">
      <input type="button" value="Topup" class="button" />
    </a>
    <div class="h1"></div>
  
</div>


<div class="container">

  <div class="panel">
    <div class="h1"></div>
    <h1>Settle Payments</h1></br>
    <h2>Settle outstanding payments!</h2></br>
    <a href="{% url 'payment_settle_page' %}">
      <input type="button" value="Settle" class="button" />
    </a>
   <div class="h1"></div>
  </div>

  <div class="panel">
    <div class="h1"></div>
    <h1>Order History</h1></br>
    <h2>View & cancel previous transactions.</h2></br>
    <a href="{% url 'request_cancellation' %}">
      <input type="button" value="View Transactions" class="button" />
    </a>
    <div class="h1"></div>
  </div>

</div>

{% endblock %}

uweflix/templates/uweflix/logout.html
<h3>Logout Test</h3>

uweflix/templates/uweflix/manage_club_account.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Account Modify
{% endblock %}
{% block header %}
Manage Club Accounts
{% endblock %}
{% block content %}

<script>
    $(function () {
        $("#id_dob").datepicker({
            dateFormat: "yy-mm-dd"
        });
    });
</script>

<div class="panel">

    {% for message in messages %}
    <p class='alert alert-success mt-3'>{{message}}</p>
    {%endfor%}


            <a class="button" href="{% url 'new_club_add_page' %}">Create New</a>


    {% if sel_clubs %}
    <form method="POST" action="{% url 'update_clubs' sel_clubs.id%}">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label> Club Name: </label>
            <input type="text" class="form-control" value="{{sel_clubs.name}}" name="name"
                placeholder="Enter Club Name">
        </div>
        <div class="form-group mb-3">
            <label> Club Street Number: </label>
            <input type="text" class="form-control" value="{{sel_clubs.street_number}}" name="street_number"
                placeholder="Enter Club Street Number">
        </div>
        <div class="form-group mb-3">
            <label> Club Street: </label>
            <input type="text" class="form-control" value="{{sel_clubs.street}}" name="street"
                placeholder="Enter Club Street">
        </div>

        <div class="form-group mb-3">
            <label> Club City: </label>
            <input type="text" class="form-control" value="{{sel_clubs.city}}" name="city"
                placeholder="Enter Club City">
        </div>



        <div class="form-group mb-3">
            <label> Club Postcode: </label>
            <input type="text" class="form-control" value="{{sel_clubs.post_code}}" name="post_code"
                placeholder="Enter Club Postcode">
        </div>
        <div class="form-group mb-3">
            <label> Club LandLine Number: </label>
            <input type="text" class="form-control" value="{{sel_clubs.landline_number}}" name="landline_number"
                placeholder="Enter Club Landline">
        </div>
        <div class="form-group mb-3">
            <label> Club Mobile Number: </label>
            <input type="text" class="form-control" value="{{sel_clubs.mobile_number}}" name="mobile_number"
                placeholder="Enter Club Mobile Number">
        </div>
        <div class="form-group mb-3">
            <label> Club Email: </label>
            <input type="text" class="form-control" value="{{sel_clubs.email}}" name="email"
                placeholder="Enter Club Email">
        </div>

        <div class="text-center mt-4">
            <button type="submit" class="btn btn-success">UPDATE</button>
        </div>
</div>

</form>

{% else %}

<form method="POST" action="{% url 'new_club_add_page' %}">
    {% csrf_token %}
    <div class="form-group mb-3">
        <label> Club Name: </label>
        <input type="text" class="form-control" name="name" placeholder="Enter Club Name">
    </div>
    <div class="form-group mb-3">
        <label> Club Street Number: </label>
        <input type="text" class="form-control" name="street_number" placeholder="Enter Club Street Number">
    </div>
    <div class="form-group mb-3">
        <label> Club Street: </label>
        <input type="text" class="form-control" name="street" placeholder="Enter Club Street">
    </div>
    <div class="form-group mb-3">
        <label> Club City: </label>
        <input type="text" class="form-control" name="city" placeholder="Enter Club City">
    </div>
    <div class="form-group mb-3">
        <label> Club Postcode: </label>
        <input type="text" class="form-control" name="post_code" placeholder="Enter Club Postcode">
    </div>
    <div class="form-group mb-3">
        <label> Club LandLine Number: </label>
        <input type="text" class="form-control" name="landline_number" placeholder="Enter Club Landline Number">
    </div>
    <div class="form-group mb-3">
        <label> Club Mobile Number: </label>
        <input type="text" class="form-control" name="mobile_number" placeholder="Enter Club Mobile Number">
    </div>
    <div class="form-group mb-3">
        <label> Club Email: </label>
        <input type="text" class="form-control" name="email" placeholder="Enter Club Email">
    </div>


    <div class="text-center mt-4">
        <button type="submit" class="button">SAVE</button>
    </div>
    </div>
</form>


{% endif %}

<div class="mt-5">
    <table class="table table-striped" style="vertical-align:middle;">
        <thead>
            <tr>
                <th scope="col">Club No.</th>
                <th scope="col">Club Name</th>
                <th scope="col">Club Street Number</th>
                <th scope="col">Club Street</th>
                <th scope="col">Club City</th>
                <th scope="col">Club Postcode</th>
                <th scope="col">Club LandLine Number</th>
                <th scope="col">Club Mobile Number</th>
                <th scope="col">Club Email</th>
                <th scope="col">Edit</th>
                <th>Delete</h1>
            </tr>
        </thead>
        <tbody>
            {% for i in club_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{i.name}}</td>
                <td>{{i.street_number}}</td>
                <td>{{i.street}}</td>
                <td>{{i.city}}</td>
                <td>{{i.post_code}}</td>
                <td>{{i.landline_number}}</td>
                <td>{{i.mobile_number}}</td>
                <td>{{i.email}}</td>
                <td>
                    <a href="{% url 'edit_clubs' i.id%}" class="btn btn-success">EDIT</a>
                </td>
                <td>
                    <a href="{% url 'delete_clubs' i.id%}" class="btn btn-danger">DELETE</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

</div>





{% endblock %}

uweflix/templates/uweflix/new_account_added_page.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
<form method="post" class="form-group">

    {% csrf_token %} {{ form }}

    <button type="submit" class="button">Add Rep</button>

    </form>
{% endblock %}
{% block content %}
<h2>Welcome Add Rep Here<h2>
    <form method="post" class="form-group">

        {% csrf_token %} {{ form }}

        <button type="submit" class="button">Add Rep</button>

        </form>
{% endblock %}

uweflix/templates/uweflix/now_playing.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Now Playing Movies
{% endblock %}
{% block header %}
Now Playing Movies
{% endblock %}
{% block content %}

<ul>
    {% for movie in movies %}
    <div class="panel">
            <h2>{{ movie.title }}</h2>
            <p>{{ movie.overview }}</p>
            <p>{{ movie.id }}</p>
            <p>{{ movie.poster_path }}</p>
            <img src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ movie.title }} Poster">
    </div>
    {% endfor %}
</ul>

{% endblock %}

uweflix/templates/uweflix/update_accounts_form_page.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Manage Accounts
{% endblock %}
{% block header %}
Manage Accounts
{% endblock %}
{% block content %}

<script>
    $( function() {
      $( "#id_dob" ).datepicker({
          dateFormat: "yy-mm-dd"
      });
    } );
</script>


<div class="container mt-3">

    {% for message in messages %}
    <p class='alert alert-success mt-3'>{{message}}</p>
    {%endfor%}

    {% if sel_user %}
    <form method="POST" action="{% url 'update_user' sel_user.id%}">
      {% csrf_token %}
      <div class="form-group mb-3"> 
        <label> First Name: </label>
        <input type="text" class="form-control" value="{{sel_user.first_name}}" name="first_name" placeholder="Enter First Name">
    </div>
    <div class="form-group mb-3"> 
      <label> Last Name: </label>
      <input type="text" class="form-control" value="{{sel_user.last_name}}" name="last_name" placeholder="Enter Last Name">
  </div>
     <div class="form-group mb-3"> 
         <label> User Name: </label>
         <input type="text" class="form-control" value="{{sel_user.username}}" name="username" placeholder="Enter Username">
     </div>

     <div class="form-group mb-3"> 
         <label> Enter Email: </label>
         <input type="text" class="form-control" value="{{sel_user.email}}" name="email" placeholder="Enter Email">
     </div>

         <div class="text-center mt-4">
             <button type="submit" class="btn btn-success">UPDATE</button>
         </div>
     </div> 
 </form>

    {% else %}

    <form method="POST" action="{% url 'add_user' %}">
         {% csrf_token %}
         <div class="form-group mb-3"> 
          <label> First Name: </label>
          <input type="text" class="form-control" name="first_name" placeholder="Enter First Name">
      </div>
      <div class="form-group mb-3"> 
        <label> Last Name: </label>
        <input type="text" class="form-control" name="last_name" placeholder="Enter Last Name">
    </div>
        <div class="form-group mb-3"> 
            <label> User Name: </label>
            <input type="text" class="form-control" name="username" placeholder="Enter Username">
        </div>

        <div class="form-group mb-3"> 
            <label> Enter Email: </label>
            <input type="text" class="form-control" name="email" placeholder="Enter Email">
        </div>

            <div class="text-center mt-4">
                <button type="submit" class="button">SAVE</button>
            </div>
        </div> 
    </form>

    {% endif %}

    <div class="mt-5" >
        <table class="table table-striped" style="vertical-align:middle;">
            <thead>
              <tr>
                <th scope="col">User No.</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Edit</th>
                <th>Delete</h1>
              </tr>
            </thead>
            <tbody>
                {% for i in user_list %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{i.first_name}}</td>
                <td>{{i.last_name}}</td>
                <td>{{i.username}}</td>
                <td>{{i.email}}</td>
                <td>
                    <a href="{% url 'edit_user' i.id%}" class="btn btn-success">EDIT</a>
                </td>
                <td>
                    <a href="{% url 'delete_user' i.id%}" class="btn btn-danger">DELETE</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
    
</div>

{% endblock %}